default: &default
  adapter: mysql2
  pool: 5
  timeout: 5000
  encoding: utf8
  host: localhost
  username: <%= ENV['DB_USER_NAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>

development:
  <<: *default
  database: db/vtex_development

test:
  <<: *default
  database: db/vtex_test

production:
  <<: *default
  database: db/vtex_production
